### ISSUE TITLE
IOException in metadata cache

### ISSUE THREAD

**Issue by wodka** [schmittjoh/JMSDiExtraBundle#235]
in symfony 2.8 the following error shows up when I navigate between pages (before the toolbar shows up) in the app_dev environment.

```
IOException in Filesystem.php line 165:
Failed to remove directory "/var/www/app/cache/dev/jms_diextra/metadata".
in Filesystem.php line 165
at Filesystem->remove('/var/www/app/cache/dev/jms_diextra/metadata') in JMSDiExtraExtension.php line 162
at JMSDiExtraExtension->configureMetadata(array('cache' => 'file'), object(ContainerBuilder), '%kernel.cache_dir%/jms_diextra/metadata') in JMSDiExtraExtension.php line 73
at JMSDiExtraExtension->load(array(array('locations' => array('all_bundles' => false, 'bundles' => array(), 'directories' => array('/var/www/app/../src/App/')))), object(ContainerBuilder)) in MergeExtensionConfigurationPass.php line 55
at MergeExtensionConfigurationPass->process(object(ContainerBuilder)) in MergeExtensionConfigurationPass.php line 39
at MergeExtensionConfigurationPass->process(object(ContainerBuilder)) in Compiler.php line 107
at Compiler->compile(object(ContainerBuilder)) in ContainerBuilder.php line 589
at ContainerBuilder->compile() in bootstrap.php.cache line 2687
at Kernel->initializeContainer() in bootstrap.php.cache line 2465
at Kernel->boot() in bootstrap.php.cache line 2496
at Kernel->handle(object(Request)) in app_dev.php line 37
```

right now I disable the cache for the dev environment:
```yaml
jms_di_extra:
    metadata:
        cache: "none"
```

**Comment by Ener-Getick** [comment]
Try to run ``app/console cache:clear --env=prod``

**Comment by wodka** [comment]
tried that - same error occurs.

this did not happen with symfony 2.7, error is always the line to remove the metadata folder

**Comment by Ener-Getick** [comment]
sorry I just saw that you're using the dev environment. Did you try this command in the dev env?

**Comment by wodka** [comment]
what I did:
```
rm -rf app/cache/*
app/console cache:clear --dev
```

-> same result sadly :(

**Comment by Ener-Getick** [comment]
Can you try to replace [this line](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/DependencyInjection/JMSDiExtraExtension.php#L155) by [this](https://gist.github.com/Ener-Getick/c3bdf71c4bb97008d246) and tell me if it works please?

**Comment by wodka** [comment]
checking for the directory fixes the issue - no more errors with your change

**Comment by Ener-Getick** [comment]
Ok then we should create a patch for this ☺

**Comment by Ener-Getick** [comment]
Fixed by https://github.com/schmittjoh/JMSDiExtraBundle/pull/236

**Comment by jqin** [comment]
I'm currently using version 1.8.1 of this bundle which includes the fix but am still running into this issue. Here are the permissions on that directory:

`drwxr-xr-x. 2 www-data www-data 20480 Oct 11 23:13 metadata`

Is there any other way that this issue can occur?

**Comment by wodka** [comment]
can you show the permissions of cache/dev/jms_diextra and cache/dev?

what is the exact error message?

**Comment by jqin** [comment]
Here are the permissions of those two directories:
```
~:/var/www/app/app# ls -l cache/
total 8
drwxrwxr-x. 9 www-data www-data 4096 Oct 12 03:00 12_factor
~:/var/www/app/app# ls -l cache/12_factor | grep jms_diextra
drwxrwxr-x.  5 www-data www-data   4096 Oct 12 02:07 jms_diextra
```

Also here's the exact error message:
```
PHP Fatal error:  Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to remove directory "/var/www/app/app/cache/12_factor/jms_diextra/met
adata".' in /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:145
Stack trace:
#0 /var/www/app/vendor/jms/di-extra-bundle/DependencyInjection/JMSDiExtraExtension.php(157): Symfony\Component\Filesystem\Filesystem->remove('/var/www/app/ap...')
#1 /var/www/app/vendor/jms/di-extra-bundle/DependencyInjection/JMSDiExtraExtension.php(67): JMS\DiExtraBundle\DependencyInjection\JMSDiExtraExtension->configureMetadata(Array, Obje
ct(Symfony\Component\DependencyInjection\ContainerBuilder), '%kernel.cache_d...')
#2 /var/www/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php(50): JMS\DiExtraBundle\DependencyInjection\JMSDiExtraE
xtension->load(Array, Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#3 /var/www/app/vendor/symfony/symfony/src/Symfony/Compone in /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 145

Fatal error: Uncaught exception 'Symfony\Component\Filesystem\Exception\IOException' with message 'Failed to remove directory "/var/www/app/app/cache/12_factor/jms_diextra/metadata
".' in /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php on line 145

Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "/var/www/app/app/cache/12_factor/jms_diextra/metadata". in /var/www/app/vendor/symfony/symfony/src/S
ymfony/Component/Filesystem/Filesystem.php on line 145

Call Stack:
    0.0001     877408   1. {main}() /var/www/app/app/console:0
    0.2853    4546928   2. JMS\JobQueueBundle\Console\Application->__construct() /var/www/app/app/console:26
    0.3826    5407840   3. AppKernel->boot() /var/www/app/vendor/jms/job-queue-bundle/JMS/JobQueueBundle/Console/Application.php:32
    0.3826    5408064   4. Symfony\Component\HttpKernel\Kernel->boot() /var/www/app/app/AppKernel.php:91
    0.3919    5835000   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() /var/www/app/app/bootstrap.php.cache:2278
    2.9832   11399808   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() /var/www/app/app/bootstrap.php.cache:2499
    2.9848   11429928   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() /var/www/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Containe
rBuilder.php:613
    2.9848   11437176   8. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process() /var/www/app/vendor/symfony/symfony/src/Symfony/Component/Dep
endencyInjection/Compiler/Compiler.php:117
    2.9852   11449488   9. Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process() /var/www/app/vendor/symfony/symfony/src/Symfony/Component/HttpK
ernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
    5.4898   19185904  10. JMS\DiExtraBundle\DependencyInjection\JMSDiExtraExtension->load() /var/www/app/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/
MergeExtensionConfigurationPass.php:50
    5.5819   19575368  11. JMS\DiExtraBundle\DependencyInjection\JMSDiExtraExtension->configureMetadata() /var/www/app/vendor/jms/di-extra-bundle/DependencyInjection/JMSDiExtraExte
nsion.php:67
    5.5828   19747752  12. Symfony\Component\Filesystem\Filesystem->remove() /var/www/app/vendor/jms/di-extra-bundle/DependencyInjection/JMSDiExtraExtension.php:157
```

**Comment by wodka** [comment]
And you are executing the console command with the www-data user? something like "sudo -u www-data app/console yourCommand"

**Comment by jqin** [comment]
Yes, they are run as the www-data user. I have to mention though that this seems somewhat intermittent in the sense that it seems to only happen the first one or two times a specific command is run.
